#!/usr/bin/env python

# Author: Karl Dyson https://karld.blog
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# See the LICENSE file for the full text of the license.
#
# Last Updated: December 2025
#

import socket
import time
import sys
import json
import re
from prometheus_client import start_http_server, Gauge

listen_port = 8000
mgroup = "239.0.0.1"
mport = 11235
mbin = bytes(map(int, mgroup.split("."))) + bytes(4)

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.bind(("0.0.0.0", mport))
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mbin)

start_http_server(listen_port)
print(f"HTTP Server Started on tcp/{listen_port} for multicast {mgroup}:{mport}")

temp_gauge = Gauge('temperature', "Temperatures", ['friendly_name', 'sensor_name'])
while True:
	data, address = sock.recvfrom(1024)
	current_time = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
	print(f"{current_time} {address}: {data.decode()}")
	sensor = json.loads(data.decode())
	if sensor['type'] != 'temperature': continue
	sensor_name = sensor["name"]
	stripped_name = "".join(sensor_name.split())
	friendly_name = " ".join(re.sub(r"([A-Z])", r" \1", stripped_name).split())
	sensor_temperature = sensor["temperature"]
	temp_gauge.labels(friendly_name=friendly_name, sensor_name=stripped_name).set(sensor_temperature)
